### ISSUE TITLE
Capitalize service in README.MD H1

### ISSUE THREAD

**Issue by mrbullwinkle** [Azure/openai-samples#8]
![image](https://user-images.githubusercontent.com/31510320/221883481-c98e95d3-7f9b-481a-ab59-ce6171257df1.png)

Official name of the service is: "Azure OpenAI Service". On first use full name is required in Microsoft content, on subsequent uses Azure OpenAI without "Service" is allowed.

**Comment by tulasim88** [comment]
closing this
